### ISSUE TITLE
Add support for .NET Core worker SDK

### ISSUE THREAD

**Issue by k94ll13nn3** [unosquare/sshdeploy#35]
**Describe the bug**
I'm using the worker template from the dotnet cli (`dotnet new worker`) and I wanted to use sshdeploy with this project but the template has a SDK that is not supported (`Microsoft.NET.Sdk.Worker`). Would it be possible to add this SDK to the supported ones?

**To Reproduce**
1. Create a new worker project with the dotnet cli
2. Add sshdeploy
3. Push

**Expected behavior**
The application is pushed.

**Actual behavior**
```
Unhandled exception. System.ArgumentException: Project file is not of the new .csproj type.
     at Unosquare.Labs.SshDeploy.Utils.CsProjFile`1..ctor(Stream stream, Boolean leaveOpen) in C:\Unosquare\sshdeploy\Unosquare.Labs.SshDeploy\Utils\CsProjFile.cs:line 54
     at Unosquare.Labs.SshDeploy.Utils.CsProjFile`1..ctor(String filename) in C:\Unosquare\sshdeploy\Unosquare.Labs.SshDeploy\Utils\CsProjFile.cs:line 32
     at Unosquare.Labs.SshDeploy.Program.Main(String[] args) in C:\Unosquare\sshdeploy\Unosquare.Labs.SshDeploy\Program.cs:line 46
```

**Comment by geoperez** [comment]
Sure, I can take a look!

**Comment by geoperez** [comment]
@JCorrea13 can you take care to use some open-source hours this week on this issue?
